import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import './globals.css';
import clsx from 'clsx';

const poppins = Poppins({
  variable: '--font-poppins',
  weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Portofolio',
  description: 'Generated by David Haryu',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={clsx(poppins.variable, `antialiased`)}>{children}</body>
    </html>
  );
}
